Repository AY2122S2-TIC4002-F18-5/tp2, pull requests merged in 2022-04, with the labels that each got.

#134 Replaced copyright images with free royalty images.
  src/main/resources/ImagesLogin/AB3.png
  src/main/resources/ImagesLogin/contact-hero-img-blue.png
  src/main/resources/ImagesLogin/contact-img-blue.png
  src/main/resources/ImagesLogin/contact-us.jpg
  src/main/resources/ImagesLogin/contact-us.png
  src/main/resources/ImagesLogin/meet-the-team.png
  src/main/resources/ImagesLogin/meettheteam.png
  src/main/resources/ImagesLogin/remark.png
  src/main/resources/view/Login.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Chore

#136 Updated the various docs and images to the latest version in use.
  docs/UserGuide.md
  docs/images/EscSignout.png
  docs/images/Ui.png
  docs/images/loginScreen.png
Labels: type.Chore

#137 Drafted the PPP as stipulated
  build.gradle
  docs/team/gweeyc.md
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#138 Updated DG and SingletonLogin Class secure coding
  docs/DeveloperGuide.md
  src/main/java/seedu/address/SingletonLogin.java
Labels: priority.High

#140 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ExportCommand_Sequencial_Diagram.png
  docs/team/yangshuogeng.md
Labels: priority.Medium

#141 Minor Edit of main App starting method in a terminal window in UG.
  docs/UserGuide.md
Labels: type.Chore

#147 remove space from jar filename as advised.
  build.gradle
  docs/UserGuide.md
Labels: type.Chore

#148 updated UG
  docs/UserGuide.md
Labels: severity.VeryLow

#149 v1.4 Added different alert windows for email feature
  src/main/java/seedu/address/logic/EmailSender.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/main/java/seedu/address/ui/email/EmailContactAlertWindowController.java
  src/main/java/seedu/address/ui/email/EmailContactChoose.java
  src/main/java/seedu/address/ui/email/EmailContactChoosingWindowController.java
  src/main/java/seedu/address/ui/email/EmailContactNumberAlert.java
  src/main/java/seedu/address/ui/email/EmailSendSuccessfulWindow.java
  src/main/java/seedu/address/ui/email/EmailSendSuccessfulWindowController.java
  src/main/java/seedu/address/ui/email/EmailWindow.java
  src/main/java/seedu/address/ui/email/EmailWindowController.java
  src/main/resources/view/EmailContactChoosingWindow.fxml
  src/main/resources/view/EmailContactNumberAlert.fxml
  src/main/resources/view/EmailSentSuccessfulWindow.fxml
  src/main/resources/view/emailWindow.fxml
  src/main/resources/view/emailWindowTesting.fxml
Labels: priority.High

#158 Update PPP
  docs/team/yangshuogeng.md
  gradle.yml
Labels: type.Chore

#159 Update yangshuogeng.md
  docs/team/yangshuogeng.md
Labels: type.Chore
