Repository AY2122S2-TIC4002-F18-5/tp2, pull requests merged in 2022-03, with the labels that each got.

#50 Added the Java CI passing image file and url ref.
  README.md
Labels: type.Chore

#51 UG doc edited to remove generic AddressBook title
  docs/UserGuide.md
Labels: type.Chore

#55 V1.2 export to text file
  datapersonDetails.txt
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/PersonDetailsExportationManager.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Low

#56 Log Command Addition
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LogCommandParser.java
  src/main/java/seedu/address/model/person/Log.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LogCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LogCommandParserTest.java
  src/test/java/seedu/address/model/person/LogTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#60 Corrected stage hiding effect via UiManager.java modification.
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/ImagesLogin/team.png
Labels: type.Chore

#62 Done an ESC key pressed for sign out and reimpose Login Screen
  src/main/java/seedu/address/LoginController.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/SingletonLogin.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#64 added undo, redo and commit to addressbook history state
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
Labels: priority.High

#65 Do clearer seperation of code lines for MainApp start method.
  src/main/java/seedu/address/MainApp.java
Labels: type.Chore

#69 updated UG for undo and redo
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: priority.High

#70 updated DG and fixed accidentally commented code
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#71 DG work branch Update by gweeyc
  docs/DeveloperGuide.md
  docs/images/ActivityDiag_LoginScr.png
  docs/images/EscSignout.png
  docs/images/UMLClass_Singleton.png
  docs/images/loginScreen.png
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#72 Updated build.gradle for shadowjar v1.3.trial
  build.gradle
Labels: type.Chore, priority.High

#75 Sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#78 Added tag icons for remark and log commands.
  src/main/resources/ImagesLogin/logIcon.png
  src/main/resources/ImagesLogin/remark.png
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#80 Addition of Reset Button to Login Screen
  src/main/java/seedu/address/LoginController.java
  src/main/resources/view/Login.fxml
Labels: priority.High

#81 Updated the DG and UG guides for v1.3.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/EscSignout.png
  docs/images/Ui.png
  docs/images/digitalclock.png
  docs/images/loginScreen.png
  docs/index.md
Labels: type.Chore, priority.High

#82 Change color of resetButton to RED for better UX effect.
  src/main/resources/view/Login.fxml
Labels: type.Chore

#87 Updated Login Screen image files to latest versions.
  docs/images/EscSignout.png
  docs/images/loginScreen.png
Labels: type.Chore, priority.High

#88 Updated build.gradle file for shadowJar version 1.3.
  build.gradle
Labels: type.Chore

#89 Updated UG for the v1.3 period use.
  docs/UserGuide.md
Labels: type.Chore

#90 Update ug
  docs/UserGuide.md
Labels: type.Chore

#92 Updated UG
  docs/UserGuide.md
  docs/images/emailCommandPic_1.png
  docs/images/emailCommandPic_2.png
  docs/images/emailWindow.png
Labels: type.Chore

#132 Add details on difference between log and remark in App
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High
